### PR TITLE
feat: add numericpattern1.cpp

### PR DESCRIPTION
**Pull request by Deepakmukka1**
image

### CODE REVIEW

**Comment by Deepakmukka1** [comment]
@aryashah2k

**Comment by aryashah2k** [comment]
Hi there, thanks for the contribution @Deepakmukka1 . Are you a Hacktoberfest Participant, Do let me know so I can add the necessary labels :)

**Comment by Deepakmukka1** [comment]
@aryashah2k yes but you also need to add hacktober fest label to this repository , currently its not considered as valid :)

**Comment by aryashah2k** [comment]
@Deepakmukka1 I have added the `hacktoberfest` label and will review and approve the changes in the next few hours. Do check from your end if all the necessary labels are added for your contribution to be accepted by Hacktoberfest and let me know if there's any issues. I am active on Github throughout the day and will be swift to respond. For any questions, use the discussions page on the repository of your choice in this organization or use the gitter channel

**Review by aryashah2k — APPROVED** [review]
The Code and the Pattern match, great work, looking forward to see more contributions from you ! Good Luck :)

**Pull request merged**
