### PR TITLE
Added code for symbol pattern 31.

### PR DESCRIPTION
**Pull request by kashyap1905**
The code will print symbol pattern 31.

Related Issue - #717 

Sample Outputs -

Output1
Output2

### CODE REVIEW

**Comment by kashyap1905** [comment]
@aryashah2k Please review this PR.

**Comment by aryashah2k** [comment]
@kashyap1905  , please go through the Discord SWOC channel for Patternhouse. The guidelines have been updated and minimum of 10 patterns are required in a PR to get the tag of Beginner(10 points). You can assign yourself some more patterns and update this PR with 10 patterns or more for it to be accepted by SWOC for its grading policy.

I strongly suggest you to check all the messages by me on our patternhouse channel ASAP

**Comment by kashyap1905** [comment]
> @kashyap1905 , please go through the Discord SWOC channel for Patternhouse. The guidelines have been updated and minimum of 10 patterns are required in a PR to get the tag of Beginner(10 points). You can assign yourself some more patterns and update this PR with 10 patterns or more for it to be accepted by SWOC for its grading policy.
> 
> I strongly suggest you to check all the messages by me on our patternhouse channel ASAP

Okay. But unfortunately the readme for Symbol Pattern folder have been removed. So I am unable to get the pattern to code. Can you please fix this so that I can resume my work.

**Comment by aryashah2k** [comment]
Yes I removed it since the issues were wrongly linked, you and all other participants will have to view the pattern on our website and then search those from the issues tab on github and tag me to assign them to you

**Comment by kashyap1905** [comment]
> Yes I removed it since the issues were wrongly linked, you and all other participants will have to view the pattern on our website and then search those from the issues tab on github and tag me to assign them to you

Okay ! Thank You for clarification.

**Pull request closed without merging**
