### PR TITLE
alphabetic pattern 1 #158

### PR DESCRIPTION
**Pull request by aakash232**
Solved issue #158 
alphabeticpattern1.cpp

### CODE REVIEW

**Review by aryashah2k — APPROVED** [review]
Code Approved!

**Comment by aryashah2k** [comment]
Thanks for the contribution, looking forward to see more from you buddy!

**Comment by aakash232** [comment]
Welcome sir! 
1. Do we have to create one PR for each program or we can submit multiple programs in one pull request? 
2. Will the SWOC tags be added too for differentiation and tracking?

**Comment by aryashah2k** [comment]
I had participated in SWOC 1.0 and at that time we had SWOC labels and each PR was givena  difficulty score. Easy PRs had less points assigned compared to difficult PRs.

I have not received any guidelines for grading yet so when they come I will update all contributions accordingly

Since there are lot of issues for our project, I suggest you make PRs in Batches and I will grade them accordingly

**Comment by aryashah2k** [comment]
For example one of the contributors is solving 11 issues in one PR

**Pull request merged**
