### PR TITLE
30 numeric patterns added

### PR DESCRIPTION
**Pull request by Sumandeep-Kaur**
Fixes: #555 #556 #557 #558 #559 #560 #561 #562 #563 #564 #565 #566 #567 #568 #569 #570 #571 #572 #573 #574 #575 #598 #599 #600 #601 #603 #604 #605 #606 #607

### CODE REVIEW

**Comment by Sumandeep-Kaur** [comment]
@aryashah2k Numeric Pattern 247 and 248 are same. Please clarify, I will change the code accordingly.

**Comment by aryashah2k** [comment]
> @aryashah2k Numeric Pattern 247 and 248 are same. Please clarify, I will change the code accordingly.

Thanks for bringing this to my notice, please change the pattern 248 to the one shown below.
I will update the image in the backend.

Screenshot_2022-01-02-19-11-41-75

**Comment by Sumandeep-Kaur** [comment]
> > @aryashah2k Numeric Pattern 247 and 248 are same. Please clarify, I will change the code accordingly.
> 
> Thanks for bringing this to my notice, please change the pattern 248 to the one shown below. I will update the image in the backend.
> 
> Screenshot_2022-01-02-19-11-41-75

This is already there, numeric pattern 249 (there's just slight difference in alignment of 8, I guess it is some error). Please check!

**Comment by aryashah2k** [comment]
Yes, for now no changes required, will identify and rectify the pattern error and make changes accordingly. Nothing to be done from your side, your PR will get the appropriate tag counting both pattern s so no worries!

**Review by aryashah2k — APPROVED** [review]

**Pull request merged**
