### PR TITLE
Added 10 Pattern Codes

### PR DESCRIPTION
**Pull request by Srishti-Ahuja**
Added String Patterns 4-13

### CODE REVIEW

**Comment by Srishti-Ahuja** [comment]
Added 10 more Pattern Codes.
Total 20 codes in Pull Request

**Review by aryashah2k — COMMENTED** [review]
all code is tested, cannot merge since the naming convention does not match. Please remove the extra "#" from each file and I will merge it ASAP. 

Naming convention is numericpattern101.cpp

**Comment by Srishti-Ahuja** [comment]
Changed the filenames to the correct convention

**Review by aryashah2k — APPROVED** [review]
Awesome, Code Files Approved!

**Pull request merged**
