### PR TITLE
Added symbol patterns

### PR DESCRIPTION
**Pull request by Sumandeep-Kaur**
Added Symbol Patterns 8-11
#693 #694  #695 #696

### CODE REVIEW

**Comment by aryashah2k** [comment]
will merge on 10 patterns, code so far has been reviewed

**Comment by Sumandeep-Kaur** [comment]
There are no issues for Symbol Patterns 61 onwards. So should I open issues by myself?

**Comment by aryashah2k** [comment]
> There are no issues for Symbol Patterns 61 onwards. So should I open issues by myself?

New Issues have been added, you can assign ones you would like to work on

**Comment by Sumandeep-Kaur** [comment]
Added Spiral Patterns - 1, 3, 4

Spiral Pattern- 1 
Issue - #10 
Screenshot (27)

Spiral Pattern - 3
Issue - #12 
Screenshot (28)

Spiral Pattern - 4
Issue - #13 
Screenshot (29)

**Comment by Sumandeep-Kaur** [comment]
@aryashah2k I had also added 7 patterns in PR no.- 768(5 patterns) and 770(2 patterns) after Dec 5. 
Will It be considered or not?

**Comment by aryashah2k** [comment]
> @aryashah2k I had also added 7 patterns in PR no.- 768(5 patterns) and 770(2 patterns) after Dec 5. Will It be considered or not?

Will consider them with some other PR where you cover the remaining 3 to make it 10, so for example if the next pr you make 13 commits then 10 + 3 for your Previous PR(After dec 5), that's how I will adjust.

**Comment by Sumandeep-Kaur** [comment]
Added Symbol Patterns:
Pattern 71 - Issue #803 
Pattern 72 - Issue #804 
Pattern 79 - Issue #811

**Comment by Sumandeep-Kaur** [comment]
> > @aryashah2k I had also added 7 patterns in PR no.- 768(5 patterns) and 770(2 patterns) after Dec 5. Will It be considered or not?
> 
> Will consider them with some other PR where you cover the remaining 3 to make it 10, so for example if the next pr you make 13 commits then 10 + 3 for your Previous PR(After dec 5), that's how I will adjust.

Okay, that's fine! But what if I commit rest 3 patterns here with this pr making total pattern count as 20?

**Comment by aryashah2k** [comment]
> > > @aryashah2k I had also added 7 patterns in PR no.- 768(5 patterns) and 770(2 patterns) after Dec 5. Will It be considered or not?
> > 
> > 
> > Will consider them with some other PR where you cover the remaining 3 to make it 10, so for example if the next pr you make 13 commits then 10 + 3 for your Previous PR(After dec 5), that's how I will adjust.
> 
> Okay, that's fine! But what if I commit rest 3 patterns here with this pr making total pattern count as 20?

In that case it gets carried forward, instead you can add 3 more here to make it 23 and I'll adjust it.

**Comment by Sumandeep-Kaur** [comment]
> > > > @aryashah2k I had also added 7 patterns in PR no.- 768(5 patterns) and 770(2 patterns) after Dec 5. Will It be considered or not?
> > > 
> > > 
> > > Will consider them with some other PR where you cover the remaining 3 to make it 10, so for example if the next pr you make 13 commits then 10 + 3 for your Previous PR(After dec 5), that's how I will adjust.
> > 
> > 
> > Okay, that's fine! But what if I commit rest 3 patterns here with this pr making total pattern count as 20?
> 
> In that case it gets carried forward, instead you can add 3 more here to make it 23 and I'll adjust it. Let me know what will you prefer, I'll accordingly merge this PR, for now I am keeping it on hold

Ok! I'm adding 3 more patterns here in this pr.

**Comment by Sumandeep-Kaur** [comment]
Added Symbol Patterns:
Pattern 73 - Issue #805 
Pattern 74 - Issue #806 
Pattern 75 - Issue #807

**Review by aryashah2k — APPROVED** [review]

**Pull request merged**
