### PR TITLE
Resolved Issue #917

### PR DESCRIPTION
**Pull request by pranavi79**
Resolved Issue #917 #918 #919 #920 #921 #922 #923 #924 #38 #40 #41 #42
added hollow diamond symbol pattern

### CODE REVIEW

**Comment by aryashah2k** [comment]
Hi there @pranavi79 , I will be able to merge the PR once there are atleast 10 patterns. So if you check the SWOC Scoring guide for my project here's how tags are assigned:
10 patterns : Beginner tag, 10 points and so on.

So assign yourself some more issues and add it to this PR. once 10 patterns cross, I will review the code and Merge it along with updation in the sheet

**Comment by pranavi79** [comment]
> Hi there @pranavi79 , I will be able to merge the PR once there are atleast 10 patterns. So if you check the SWOC Scoring guide for my project here's how tags are assigned: 10 patterns : Beginner tag, 10 points and so on.
> 
> So assign yourself some more issues and add it to this PR. once 10 patterns cross, I will review the code and Merge it along with updation in the sheet

Thank you for letting me know, I have made necessary changes

**Comment by aryashah2k** [comment]
Cool, Also if you are willing to add 6 more patterns I will be able to add the 20 points tag. so do let me kknow if I shoudl merge it rn or wait for more patterns added in this PR

**Comment by pranavi79** [comment]
Hey I added 6 more patterns in series

**Review by aryashah2k — APPROVED** [review]

**Comment by aryashah2k** [comment]
PR Merged, make sure to assign yourself the said issues you want to work with and also join the organization so that it is easy to keep record.

**Pull request merged**
