### PR TITLE
Added 26 patterns

### LINKED ISSUE #513: Code | Numeric Pattern 162

### PR DESCRIPTION
**Pull request by Sumandeep-Kaur**
Fixes: #513 #608 #609 #610 #646 #647 #648 #649 #650 #651 #652 #653 #658 #659 #660 #661 #663 #664 #671 #674 #676 #677 #678 #914 #915 #916

### CODE REVIEW

**Comment by aryashah2k** [comment]
Should I merge the PR with easy tag or are you adding 4 more to make it medium? Let me know:)

**Comment by Sumandeep-Kaur** [comment]
> Should I merge the PR with easy tag or are you adding 4 more to make it medium? Let me know:)

Yeah you can merge, all the patterns have been completed in this repo.

**Review by aryashah2k — APPROVED** [review]

**Review by aryashah2k — APPROVED** [review]

**Comment by aryashah2k** [comment]
The remaining 16 issues have been assigned for more than a week so it is open for you too if you are comfortable with them!

**Comment by Sumandeep-Kaur** [comment]
> The remaining 16 issues have been assigned for more than a week so it is open for you too if you are comfortable with them!

They have already merged, you can close them.

**Pull request merged**
