### PR TITLE
Code for Numeric pattern 225 - 231, 234 - 236, 238 - 244.

### PR DESCRIPTION
**Pull request by Mahak008**

### CODE REVIEW

**Comment by aryashah2k** [comment]
Hi Mahak, just delete the numericpattern247.cpp since that is causing merge conflicts. As discussed yesterday, it has been already solved by another contributor. Till then I will just review the existing code files and update the same in excel sheet. Let me know when you do the needful, I will merge ASAP

**Comment by Mahak008** [comment]
> Hi Mahak, just delete the numericpattern247.cpp since that is causing merge conflicts. As discussed yesterday, it has been already solved by another contributor. Till then I will just review the existing code files and update the same in excel sheet. Let me know when you do the needful, I will merge ASAP

I have deleted. Kindly check.

**Review by aryashah2k — APPROVED** [review]

**Comment by aryashah2k** [comment]
PR merged and SWOC Score Sheet Updated!

**Comment by Mahak008** [comment]
> PR merged and SWOC Score Sheet Updated!

Thank you for the same and kindly close the issue for numeric pattern 243 in c++.

**Pull request merged**
