### PR TITLE
Added code for Symbol Pattern 45.

### PR DESCRIPTION
**Pull request by kashyap1905**
According to Readme.md, Code will print symbol pattern 94.

Related Issue - #732 

Sample Outputs -

Output1
Output2

### CODE REVIEW

**Comment by kashyap1905** [comment]
@aryashah2k  Please review this PR.

**Review by aryashah2k — COMMENTED** [review]
Please follow the naming convention in order to allow our ci cd script to automatically fetch the source code file:

The anming convention is all small eg symbolpattern45.cpp

**Comment by kashyap1905** [comment]
@aryashah2k 

I reached this issue via a link that was provided for Issue Number 94 in the readme file of Symbol Patterns in CPlusPlus-PatternHouse. But the issue says its pattern number 45. So should I add code for Pattern number 45 or pattern number 94 according to the readme file?? Please clarify!

**Comment by kashyap1905** [comment]
> Please follow the naming convention in order to allow our ci cd script to automatically fetch the source code file:
> 
> The anming convention is all small eg symbolpattern45.cpp

Made changes as instructed. Please review.

**Review by aryashah2k — APPROVED** [review]

**Pull request merged**
