### PR TITLE
feat: add numericpattern145.cpp

### PR DESCRIPTION
**Pull request by Deepakmukka1**
Pattern required:

image

Solution:

image

### CODE REVIEW

**Comment by Deepakmukka1** [comment]
@aryashah2k

**Comment by aryashah2k** [comment]
Do mention the issue number in all future PRs so I can easily close those issue whose PRs are successfully merged. I will review the code and merge soon

**Comment by Deepakmukka1** [comment]
@aryashah2k actually there is no issue opened for numeric patterns , kindly look into it

**Comment by aryashah2k** [comment]
Alright, I will create the relevant issues from my side, for now it's okay! I will merge these two PRs in the next few mins:)

**Review by aryashah2k — APPROVED** [review]
All Code has been tested and patterns match

**Review by aryashah2k — APPROVED** [review]
All Code has been tested and patterns match

**Pull request merged**
